import fs from "fs";

const packageJson = JSON.parse(fs.readFileSync("package.json", "utf8"));
const version = packageJson.version;

if (!version) {
  throw new Error("package.json is missing a version field");
}

const manifestPath = "manifest.json";
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
manifest.version = version;
fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

const versionModule = `// This file is auto-generated by scripts/sync-version.mjs
// Do not edit manually - update version in package.json instead
export const VERSION = "${version}";
`;

fs.writeFileSync("src/version.ts", versionModule);
